name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Installing deps
      run: npm install

    - name: Checking Style
      run: npm run check

    - name: Running tests
      run: npm run test
